# -*- coding: utf-8 -*-
"""SIRModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MV2i16vdYWSwTVddFvtsJ46fZPhUWX4Z
"""

#Import Packages
import scipy.integrate
import numpy
import matplotlib.pyplot as plt

#Ode`s
def SIR_model(y,t,beta,gamma):
  S,I,R = y
  dS_dt = -beta*S*I #La varianza poblacion susceptible con respecto al tiempo es la cantidad taza de infeccion por numero de poblacion suceptible por poblacion infectada
  dI_dt = beta*S*I - gamma*I #varianza de poblacion infectada  con respecto al tiempo es la taza de infeccion por el numero de poblacion susceptible por poblacion infectada
  dR_dt = gamma*I #Varianza de 
  return([dS_dt ,dI_dt ,dR_dt ])

#Initial Conditions
S0 = 0.9
I0 = 0.1
R0 = 0.0
beta = 0.35
gamma =0.1

#Time Vector
t = numpy.linspace(0,100,100)
#Result
solution = scipy.integrate.odeint(SIR_model,[S0,I0,R0],t,args=(beta,gamma))

#plot figure
plt.figure(figsize=(8,6))
plt.plot(t,solution[:,0],label='S(t)')
plt.plot(t,solution[:,1],label='I(t)')
plt.plot(t,solution[:,2],label='R(t)')
plt.grid()
plt.title('SIR Model')
plt.legend()
plt.xlabel('Time/Days')
plt.ylabel('Proportions')
plt.show()